(define (double n) (* n 2))
(define (halve n) (/ n 2))

(define (mul a b)
  (define (iter acc a b)
    (begin
      (display acc)
      (display "; ")
      (display a)
      (display "; ")
      (display b)(newline)
    )
    (cond ((= b 0) acc)
	  ((even? b) (iter acc (double a) (halve b)))
	  (else (iter (+ acc a) a (- b 1)))
    )
  )
  (if (< a b)
      (iter 0 b a)
      (iter 0 a b)
  )
)

(mul 5 6)
